---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: npm-install
spec:
  params:
    - name: node-version
      type: string
      default: '20'
  workspaces:
    - name: source
    - name: npm-cache
      optional: true
  steps:
    - name: install-root-dependencies
      image: docker.io/library/node:$(params.node-version)-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Installing root dependencies..."
        npm ci

    - name: install-subpackage-dependencies
      image: docker.io/library/node:$(params.node-version)-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Installing subpackage dependencies..."
        cd packages/react-form-wizard
        npm ci

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: npm-lint
spec:
  params:
    - name: node-version
      type: string
      default: '20'
  workspaces:
    - name: source
    - name: npm-cache
      optional: true
  steps:
    - name: eslint
      image: docker.io/library/node:$(params.node-version)-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Running ESLint..."
        npm run lint

    - name: prettier-check
      image: docker.io/library/node:$(params.node-version)-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Checking Prettier formatting..."
        npm run prettier:check

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: npm-type-check
spec:
  params:
    - name: node-version
      type: string
      default: '20'
  workspaces:
    - name: source
    - name: npm-cache
      optional: true
  steps:
    - name: type-check
      image: docker.io/library/node:$(params.node-version)-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Running TypeScript type checking..."
        npm run type-check

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: npm-build
spec:
  params:
    - name: node-version
      type: string
      default: '20'
  workspaces:
    - name: source
    - name: npm-cache
      optional: true
  steps:
    - name: build
      image: docker.io/library/node:$(params.node-version)-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Building library..."
        npm run build
      resources:
        requests:
          memory: 2Gi
          cpu: 1000m

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: playwright-component-tests
spec:
  params:
    - name: node-version
      type: string
      default: '20'
  workspaces:
    - name: source
    - name: npm-cache
      optional: true
  steps:
    - name: run-component-tests
      image: mcr.microsoft.com/playwright:v1.56.1-noble
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Running Playwright component tests..."
        npm run test:ct
      resources:
        requests:
          memory: 2Gi
          cpu: 1000m

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: playwright-e2e-tests
spec:
  params:
    - name: node-version
      type: string
      default: '20'
  workspaces:
    - name: source
    - name: npm-cache
      optional: true
  steps:
    - name: run-e2e-tests
      image: mcr.microsoft.com/playwright:v1.56.1-noble
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Running Playwright E2E tests..."
        npm run test:e2e
      resources:
        requests:
          memory: 2Gi
          cpu: 1000m

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: npm-build-storybook
spec:
  params:
    - name: node-version
      type: string
      default: '20'
  workspaces:
    - name: source
    - name: npm-cache
      optional: true
  steps:
    - name: build-storybook
      image: docker.io/library/node:$(params.node-version)-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Building Storybook..."
        npm run build-storybook
      resources:
        requests:
          memory: 2Gi
          cpu: 1000m
