import { Section, useItem, WizSelect, WizTextInput } from '@patternfly-labs/react-form-wizard';
import { ClipboardCopy, ExpandableSection, Stack, StackItem } from '@patternfly/react-core';
import React from 'react';
import PopoverHintWithTitle from '../../../common/PopoverHitWithTitle';
import { OIDCConfigHint } from '../../../common/OIDCConfigHint';
import { OIDCConfig, SelectDropdownType } from '../../../../types';
import { useTranslation } from '../../../../../../context/TranslationContext';

type RolesAndPoliciesSubStep = {
  installerRoles: SelectDropdownType[];
  supportRoles: SelectDropdownType[];
  workerRoles: SelectDropdownType[];
  oicdConfig: OIDCConfig[];
};

export const RolesAndPoliciesSubStep: React.FunctionComponent<RolesAndPoliciesSubStep> = ({
  installerRoles,
  supportRoles,
  workerRoles,
  oicdConfig,
}) => {
  const { t } = useTranslation();
  const [isOperatorRolesOpen, setIsOperatorRolesOpen] = React.useState<boolean>(true);
  const [isArnsOpen, setIsArnsOpen] = React.useState<boolean>(false);
  const { cluster } = useItem();

  const rosaCommand = `rosa create operator-roles --prefix "${cluster?.custom_operator_roles_prefix}" --oidc-config-id "${cluster?.byo_oidc_config_id}" --hosted-cp --installer-role-arn ${cluster?.installer_role_arn}`;

  return (
    <>
      <Section label={t('Account roles')}>
        <WizSelect
          path="cluster.installer_role_arn"
          label={t('Installer role')}
          placeholder={t('Select an Installer role')}
          labelHelp={t('An AWS IAM role used by the ROSA installer {SHOULD BE LINK HERE}')}
          options={installerRoles}
          required
        />
        <ExpandableSection
          isExpanded={isArnsOpen}
          onToggle={() => setIsArnsOpen(!isArnsOpen)}
          toggleText={t('Amazon Resource Names (ARNs)')}
        >
          <WizSelect
            path="cluster.support_role_arn"
            label={t('Support role')}
            placeholder={t('Select an AWS infrastructure account')}
            labelHelp={t(
              'An IAM role used by the Red Hat Site Reliability Engineering (SRE) support team. The role is used with the corresponding policy resource to provide the Red Hat SRE support team with the permissions required to support ROSA clusters.'
            )}
            options={supportRoles}
            required
          />
          <WizSelect
            path="cluster.worker_role_arn"
            label={t('Worker role')}
            placeholder={t('Select an AWS infrastructure account')}
            labelHelp={t(
              'An IAM role used by the ROSA compute instances. The role is used with the corresponding policy resource to provide the compute instances with the permissions required to manage their components.'
            )}
            options={workerRoles}
            required
          />
        </ExpandableSection>
      </Section>
      <Section label="Operator roles">
        <Stack>
          <StackItem>
            <WizSelect
              path="cluster.byo_oidc_config_id"
              label={t('OIDC config ID')}
              required
              placeholder={t('Selec an OIDC config ID')}
              labelHelp={t(
                'The OIDC configuration ID created by running the command: rosa create oidc-config'
              )}
              options={oicdConfig.map((config) => {
                return {
                  label: config.label,
                  value: config.value,
                  description: config.issuer_url,
                };
              })}
            />
          </StackItem>
          <StackItem>
            <PopoverHintWithTitle
              displayHintIcon
              title={t('Create a new OIDC config id')}
              bodyContent={<OIDCConfigHint />}
            />
          </StackItem>
        </Stack>

        <ExpandableSection
          isExpanded={isOperatorRolesOpen}
          onToggle={() => setIsOperatorRolesOpen(!isOperatorRolesOpen)}
          toggleText={t('Operator role prefix')}
        >
          <WizTextInput
            path="cluster.custom_operator_roles_prefix"
            label={t('Operator roles prefix')}
            labelHelp={t(
              'You can specify a custom prefix for the Operator AWS IAM roles. {LINK HERE: Learn more and see examples}.'
            )}
            helperText={t(
              '32 characters maximum. This is autogenerated by the cluster name, but you can cahnge it.'
            )}
            required
          />
          <ClipboardCopy
            variant="expansion"
            copyAriaLabel="Copy read-only example"
            isReadOnly
            hoverTip={t('Copy')}
            clickTip={t('Copied')}
            style={{ marginTop: '1rem' }}
          >
            {rosaCommand}
          </ClipboardCopy>
        </ExpandableSection>
      </Section>
    </>
  );
};
