import {
  Section,
  Step,
  WizSelect,
  WizTextInput,
} from "@patternfly-labs/react-form-wizard";
import {
  ClipboardCopy,
  ExpandableSection,
  HelperText,
  HelperTextItem,
} from "@patternfly/react-core";
import React from "react";

type RolesAndPoliciesSubStep = {
  installerRoles: any;
  supportRoles: any;
  workerRoles: any;
};

export const RolesAndPoliciesSubStep: React.FunctionComponent<
  RolesAndPoliciesSubStep
> = ({ installerRoles, supportRoles, workerRoles }) => {
  const [isOperatorRolesOpen, setIsOperatorRolesOpen] =
    React.useState<boolean>(true);
  const [isArnsOpen, setIsArnsOpen] = React.useState<boolean>(false);
  return (
    <>
      <Section label="Account roles">
        <WizSelect
          path="metadata.accountroles"
          label="Installer role"
          placeholder="Select an Installer role"
          labelHelp="An AWS IAM role used by the ROSA installer {SHOULD BE LINK HERE}"
          options={installerRoles}
          required
        />
        <ExpandableSection
          isExpanded={isArnsOpen}
          onToggle={() => setIsArnsOpen(!isArnsOpen)}
          toggleText="Amazon Resource Names (ARNs)"
        >
          <WizSelect
            path="metadata.supportroles"
            label="Support role"
            placeholder="Select an AWS infrastructure account"
            labelHelp="An IAM role used by the Red Hat Site Reliability Engineering (SRE) support team. The role is used with the corresponding policy resource to provide the Red Hat SRE support team with the permissions required to support ROSA clusters."
            options={supportRoles}
            required
          />
          <WizSelect
            path="metadata.workerroles"
            label="Worker role"
            placeholder="Select an AWS infrastructure account"
            labelHelp="An IAM role used by the ROSA compute instances. The role is used with the corresponding policy resource to provide the compute instances with the permissions required to manage their components."
            options={workerRoles}
            required
          />
        </ExpandableSection>
      </Section>
      <Section label="Operator roles">
        <ExpandableSection
          isExpanded={isOperatorRolesOpen}
          onToggle={() => setIsOperatorRolesOpen(!isOperatorRolesOpen)}
          toggleText="Amazon Resource Names (ARNs)"
        >
          <WizTextInput
            path="metadata.operatorRolesPrefix"
            label="Operator roles prefix"
            labelHelp="You can specify a custom prefix for the Operator AWS IAM roles. {LINK HERE: Learn more and see examples}."
            helperText="32 characters maximum. This is autogenerated by the cluster name, but you can cahnge it."
            required
          />
          <ClipboardCopy copyAriaLabel="Copy read-only example" isReadOnly hoverTip="Copy" clickTip="Copied" style={{marginTop: "1rem"}}>
            rosa create operator-roles --prefix "mycluster1-d0u8" --oidc-config-id "22qa79cdjskahfkaslew3jrklnkkalsdjnfmdallmnlmas" --hosted-cp --installer-role-arn arn:aws:iam::93845209348:/role/ManagedOpenshift-HCP-ROSA-Installer-Role
          </ClipboardCopy>
        </ExpandableSection>
      </Section>
      
    </>
  );
};
